version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-18-232-143-90.compute-1.amazonaws.com
            database: d2d8k9a4g8mrjr
            schema: public
            user: ejanezndcroehi
            password: 9537dd1e565cf3f0cb84d380dfa10d88185521dd532b0ec1344aeb8b08f1aff8
            ssl: true
            rawAccess: true
            port: '5432'
            migrations: true