projects:
    prisma:
        schema: prisma/prisma.yml
        extensions:
            endpoints:
                default: http://localhost:4466/food/dev
            codegen:
                generates:
                    ./src/generated/prisma.graphql:
                        plugins:
                            - schema-ast