version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-3-215-83-17.compute-1.amazonaws.com
            database: davo9idvroqol5
            schema: public
            user: itciudpnsxtelr
            password: 73e6426fb04129c4b1f86187f8a91f8257badcc82d6aef94eae2c6dba3a53f8f
            ssl: true
            rawAccess: true
            port: '5432'
            migrations: true